import { Option } from "payload/dist/fields/config/types";
import { option } from "../../../option";

// Options from http://dnd5e.wikidot.com/#toc3
export const backgroundOptions: Option[] = [
    option("Acolyte"),
    option("Acolyte"),
    option("Anthropologist"),
    option("Archaeologist"),
    option("Athlete"),
    option("Charlatan"),
    option("City Watch"),
    option("Clan Crafter"),
    option("Cloistered Scholar"),
    option("Courtier"),
    option("Criminal"),
    option("Entertainer"),
    option("Faceless"),
    option("Faction Agent"),
    option("Far Traveler"),
    option("Feylost"),
    option("Fisher"),
    option("Folk Hero"),
    option("Gladiator"),
    option("Guild Artisan"),
    option("Guild Merchant"),
    option("Haunted One"),
    option("Hermit"),
    option("House Agent"),
    option("Inheritor"),
    option("Investigator (SCAG)"),
    option("Investigator (VRGR)"),
    option("Knight"),
    option("Knight of the Order"),
    option("Marine"),
    option("Mercenary Veteran"),
    option("Noble"),
    option("Outlander"),
    option("Pirate"),
    option("Sage"),
    option("Sailor"),
    option("Shipwright"),
    option("Smuggler"),
    option("Soldier"),
    option("Spy"),
    option("Urban Bounty Hunter"),
    option("Urchin"),
    option("Uthgardt Tribe Member"),
    option("Waterdhavian Noble"),
    option("Witchlight Hand"),
    option("Black Fist Double Agent"),
    option("Dragon Casualty"),
    option("Iron Route Bandit"),
    option("Phlan Insurgent"),
    option("Stojanow Prisoner"),
    option("Ticklebelly Nomad"),
    option("Caravan Specialist"),
    option("Earthspur Miner"),
    option("Harborfolk"),
    option("Mulmaster Aristocrat"),
    option("Phlan Refugee"),
    option("Cormanthor Refugee"),
    option("Gate Urchin"),
    option("Hillsfar Merchant"),
    option("Hillsfar Smuggler"),
    option("Secret Identity"),
    option("Shade Fanatic"),
    option("Trade Sheriff"),
    option("Gate Warden"),
    option("Giant Foundling"),
    option("Knight of Solamnia"),
    option("Mage of High Sorcery"),
    option("Planar Philosopher"),
    option("Rune Carver"),
    option("Ashari"),
    option("Celebrity Adventurer's Scion"),
    option("Failed Merchant"),
    option("Gambler"),
    option("Plaintiff"),
    option("Rival Intern"),
    option("Dissenter"),
    option("Initiate"),
    option("Vizier"),
    option("Inquisitor"),
    option("Azorius Functionary"),
    option("Boros Legionnaire"),
    option("Dimir Operative"),
    option("Golgari Agent"),
    option("Gruul Anarch"),
    option("Izzet Engineer"),
    option("Orzhov Representative"),
    option("Rakdos Cultist"),
    option("Selesnya Initiate"),
    option("Simic Scientist"),
    option("Lorehold Student"),
    option("Prismari Student"),
    option("Quandrix Student"),
    option("Silverquill Student"),
    option("Witherbloom Student"),
    option("Grinner"),
    option("Volstrucker Agent"),
    option("Astral Drifter"),
    option("Wildspacer"),
];
